export * from './types';
export * from './tablas';
export { computeLey73 } from './ley73';
export { computeLey97 } from './ley97';
export { computeTransicion } from './transicion';
export type { ResultadoTransicion } from './transicion';
export { computeProyectoMod40 } from './mod40-proyecto';
export type { EntradaProyecto } from './mod40-proyecto';
export * from './contrafactual';
export * from './tablas-contrafactual';
export { getHistoriaLaboral } from './historia-laboral';
export type { EmpleoHistorial } from './historia-laboral';
export * from './eventos-laborales';
