-- 171: las 15 fichas revisadas por Raul el 21-sep (claude/73): T1–T4 de tema, O1–O11 de oportunidad.

insert into trol3.fichas (codigo, tipo, titulo, oportunidades, orden, frase, cuando_aplica, como_explicarlo, preguntas, documentos, solo_asesor, en_diagnostico) values
  ($f$T1$f$, 'tema', $f$Ley 73 o Ley 97$f$, '{}', 10, $f$Si empezaste a cotizar antes del 1 de julio de 1997 eres Ley 73 y tu pensión la calcula y la paga el IMSS de por vida; si empezaste después eres Ley 97 y tu pensión sale de lo que juntaste en tu AFORE.$f$, null, $f$1. Ley 73 depende de tres cosas: tus semanas, tu salario promedio de las últimas 250 semanas y la edad a la que te retiras. Requisitos: 500 semanas, 60 años y derechos vigentes.
2. Ley 97 depende de tu saldo (AFORE + Infonavit) y de tu edad. Requisitos: 60 años y un mínimo de semanas que sube cada año: 875 en 2026, +25 por año hasta 1,000 en 2031.
3. Una persona puede tener derechos en más de un régimen (IMSS e ISSSTE). Identifícalo; **el cruce de estrategias entre regímenes es asesoría avanzada**.$f$, $f$- *"¿Puedo escoger?"* — Si tienes derecho a Ley 73 sí puedes elegir pensionarte por Ley 97 si lo prefieres; en general no conviene. Lo que sí pasa es que un Ley 73 que pierde sus derechos queda bajo reglas de Ley 97 (ver T2).
- *"Me dijeron que soy 97 pero yo trabajé desde los 80"* — Puede ser cierto: si tu NSS es anterior a 1997 y tu primera cotización registrada es posterior, hay semanas que el IMSS no te está reconociendo. Ver ficha **O2**.$f$, null, null, $f$Resumen de su situación.$f$),
  ($f$T2$f$, 'tema', $f$Conservación de derechos (Ley 73)$f$, '{}', 20, $f$Al dejar de cotizar conservas tu derecho a pensionarte por Ley 73 durante la cuarta parte del tiempo que cotizaste; si se vence, hay que volver a cotizar para recuperarlo.$f$, null, $f$1. El dato que importa es una fecha: **cuándo vencen** (en el expediente, "fin de conservación"). Ya contempla si perdió los derechos y volvió a cotizar sin completar lo necesario: una última cotización posterior al vencimiento **no es error de datos**.
2. Qué pasa si se vencen: te aplican las reglas de Ley 97. Con menos de 875 semanas puede haber **negativa de pensión**; con más, una pensión muy chica **y el IMSS se queda con tu saldo de AFORE e Infonavit** para pagarla.
3. Cómo se recuperan: cotizando **12 meses consecutivos**. Sin patrón, la vía es Modalidad 10 (ficha **O4**).$f$, $f$- *"¿Cuánto tiempo tengo?"* — Da la fecha del expediente, no una regla general.
- *"¿Y si ya se me vencieron hace años?"* — Se recuperan igual, con los 12 meses. Lo que cambia es si con ese año llegas a 500 semanas: por eso el piso es 450.$f$, null, $f$Dinero en riesgo (fórmula autorizada por Raul): `(RCV 97 ÷ 3 + SAR 92) × 0.8`. Sirve para dimensionar; **el primer mensaje nunca lleva cifra** — el dolor es la negativa, no el saldo. Con menos de 450 semanas (`r1_lejos`) **no se promete recuperar Ley 73**: necesitarían 4 o 5 años de Modalidad 10.$f$, $f$Resumen de su situación · Estrategia y oportunidades.$f$),
  ($f$T3$f$, 'tema', $f$La edad de retiro$f$, '{}', 30, $f$En Ley 73 la pensión se paga al 75% a los 60 años y sube 5% por cada año hasta el 100% a los 65; esperar la sube de por vida, retirarte antes la baja pero la cobras más tiempo.$f$, null, $f$1. Enseña la tabla: 60 → 75% · 61 → 80% · 62 → 85% · 63 → 90% · 64 → 95% · 65 → 100%.
2. El IMSS cuenta la edad con fracción: con 6 meses cumplidos ya aplica el siguiente escalón (60 años y 6 meses = 80%). Por eso la **fecha** de trámite importa tanto como el año.
3. En Ley 97 es distinto: cada año extra suma aportaciones y rendimientos, y pensionarte a los 65 o más da acceso al Fondo de Pensiones para el Bienestar (tope alrededor de $17,885 al mes en 2026).
4. No lo discutas en abstracto: mueve la edad en la calculadora y que vea los dos números.$f$, $f$- *"¿Me conviene esperar?"* — Depende de si sigue cotizando, de si sus derechos aguantan hasta esa edad (T2) y de si necesita el ingreso hoy. Cada mes sin cobrar es pensión que no regresa.
- *"¿Y el retroactivo?"* — Ver **O6**.$f$, null, null, $f$Estrategia y oportunidades (escenarios).$f$),
  ($f$T4$f$, 'tema', $f$Pensión mínima garantizada$f$, '{}', 40, $f$Si tu cálculo sale por debajo de la mínima, recibes la mínima; en Ley 73 su monto depende del **último año en que cotizaste**.$f$, null, $f$1. Ley 73: quien cotice al menos una vez en 2026 tiene una mínima de alrededor de **$10,635** al mes. Quien dejó de cotizar antes se queda con la mínima de ese año (**"mínima congelada"**). Una sola cotización en el año la descongela.
2. Además de la pensión, en Ley 73 recibe en efectivo su Infonavit no utilizado y su SAR 92 y Retiro 97.
3. Ley 97: la mínima depende de edad, semanas y salario promedio de toda la vida; en 2026 va de alrededor de $3,500 a $11,200. Si AFORE + Infonavit no alcanzan para pagarla, **el IMSS toma los dos saldos** y complementa (ver **O7**).
4. Filosofía Trol: buscar al menos la mínima garantizada; vale mucho más que retirar el dinero de la AFORE, y trae servicio médico del IMSS de por vida.$f$, null, null, $f$Es el argumento de la campaña C2. El corte correcto es "¿cotizó en 2026?", no "¿hace más de dos años?". Confirmado por Raul: si cotizó en 2026 le toca esa mínima; si no, será menor, con algún retroactivo.$f$, $f$Resumen de su situación.$f$),
  ($f$O1$f$, 'oportunidad', $f$Recuperar semanas que el IMSS no te reconoce$f$, '{reconocimiento_semanas}', 50, $f$Semanas que sí trabajaste y que el IMSS no te está contando; cada 52 que se recuperan suben tu pensión.$f$, $f$Declaró 26 semanas o más por encima de las reconocidas, **o** el año de su NSS es anterior a su primera cotización registrada (cualquier brecha). El sistema clasifica el caso: NSS anterior a 1987, posible seguro facultativo, o edad no universitaria.$f$, $f$1. No es que "se las quitaron": no están ligadas a su número. Pasa con patrones que ya cerraron, con registros en papel anteriores a la digitalización y con un segundo NSS.
2. Se demuestra con papeles y se corrige ante el IMSS.
3. Distingue de las semanas **descontadas**: ésas son por retiros por desempleo y se recuperan reintegrando el dinero — es otro trámite.$f$, $f$- *"¿Y si la empresa ya no existe?"* — Se puede con recibos, constancias, avisos de alta o credenciales de la época.
- *"¿Cuánto tarda?"* — De 1 a 2 meses.
- *"¿Y si no aparecen?"* — Se cobra el 50% por adelantado, por la búsqueda, y el otro 50% sólo si el resultado es exitoso.$f$, $f$Cliente: identificación oficial vigente y CURP. Trol: acta de nacimiento (se saca desde Documentos), constancia de semanas, entrega al gestor, resultado del gestor, consulta al IMSS de verificación.$f$, $f$Producto "Búsqueda manual de semanas": Trol cobra **$20,000**, el gestor cuesta $15,000. El honorario se ajusta por caso (puede incluir varios temas). Ejecuta Gestor Jordan o Trol. **Promete revisión, no semanas.**$f$, $f$Lectura de su historia laboral · Gestorías.$f$),
  ($f$O2$f$, 'oportunidad', $f$Recuperar Ley 73$f$, '{recuperar_ley73}', 60, $f$Apareces como Ley 97, pero tu número de seguridad social es anterior a 1997: si se localizan tus semanas de antes, regresas a Ley 73.$f$, $f$Ley 97 con NSS de 1996 o anterior y primera cotización registrada posterior. 248 personas al 10-sep.$f$, $f$1. El NSS se asigna cuando alguien te da de alta por primera vez. Si el tuyo es de 1989 y tu historia empieza en 2001, falta un pedazo.
2. La diferencia no es de semanas, es de **régimen**: pasar de una pensión que sale de tu AFORE a una que calcula y paga el IMSS de por vida.
3. Se logra con uno de dos trámites, según el caso: búsqueda de semanas o unificación de dos NSS. Eso lo decide el asesor al ganar la oportunidad.$f$, $f$- *"¿Es seguro que regreso a Ley 73?"* — No: depende de que las semanas aparezcan y se reconozcan. Lo seguro es que vale la pena buscarlas.$f$, $f$Los mismos siete pasos de **O1**.$f$, $f$Es la oportunidad de mayor valor por cliente del catálogo de gestoría. Mismos productos y precios que O1 y O3. **No digas "te regresamos a Ley 73"; di "buscamos lo que te regresa a Ley 73".**$f$, $f$Lectura de su historia laboral · Gestorías · Estrategia.$f$),
  ($f$O3$f$, 'oportunidad', $f$Corregir tu registro en el IMSS$f$, '{inconsistencia_imss,unificacion_nss}', 70, $f$El IMSS no nos entrega tu información porque algo no cuadra en tu registro —un nombre mal escrito, dos números de seguridad social—, y mientras no se corrija cualquier cálculo es a ciegas.$f$, $f$Inconsistencia reportada por el proveedor, o sin ley con consultas fallidas; o `nss` y `nss_alterno` válidos y distintos (el segundo NSS hoy lo captura el asesor).$f$, $f$1. **Primero descarta el dedazo**: el cliente puede revisar y corregir su CURP desde su cuenta, y eso relanza la búsqueda sola. Sólo cuando él confirma que su CURP está bien es un problema de registro.
2. Si son dos NSS, sus semanas están repartidas: unificarlas es un trámite con resultado muy visible.
3. Es lo primero que se arregla. Todo lo demás depende de esto.$f$, null, $f$Los siete pasos de O1. Cuando la consulta normal falla, está la consulta por **ventanilla** (Jordan, requiere NSS de 11 dígitos).$f$, $f$"Actualización de datos ante el IMSS": Trol cobra **$8,000**, costo $3,500. "Unificación de cuentas": **$10,000**, costo $4,300. La consulta por ventanilla le cuesta a Trol $52.$f$, $f$Gestorías.$f$),
  ($f$O4$f$, 'oportunidad', $f$Recuperar tus derechos de Ley 73 con Modalidad 10$f$, '{reactivacion_mod10}', 80, $f$Tus derechos de Ley 73 se vencieron (o están por vencer) y se recuperan cotizando doce meses seguidos por tu cuenta; hay un programa que lo financia.$f$, $f$Ley 73 · derechos no vigentes o que vencen en menos de 180 días · **más de 450 semanas brutas** (no importan las descontadas) · 58.8 años o más · no pensionado. 687 personas al 10-sep.$f$, $f$1. Empieza por lo que pierde (T2): sin derechos, negativa o pensión mínima de Ley 97, y su saldo se va.
2. La salida: **Modalidad 10**. La puede tomar cualquiera, en cualquier ley, sin patrón. Son **12 meses consecutivos**.
3. Si ya tiene 60, termina el año y se pensiona. Si está por cumplirlos, termina de pagar y ya tiene la edad.
4. El programa cubre los pagos; el plan se arma caso por caso.$f$, $f$- *"¿Cuánto cuesta?"* — Se revisa con sus números y las diferentes opciones de financiamiento.
- *"¿Y si me atraso un mes?"* — Se rompe la continuidad y el año vuelve a empezar. Es la regla que más hay que explicar.$f$, $f$Constancia de semanas (Trol) → definir la vía de reactivación (Trol) → alta en Modalidad 10 (Viraal) → comprobante del primer pago (cliente) → consulta de verificación (Trol).$f$, $f$Se financian **14 pagos** para tener margen sobre los 12. El riesgo del producto son los 12 consecutivos, por eso conviene **pagarle directo al IMSS** y no entregarle el dinero al cliente. Cobro al cliente y comisión de Trol: depende del aliado y del proyecto particular. Con $200,000 o más en riesgo (`r1c`, `r4_asesor`) no es de campaña: va directo contigo.$f$, $f$Estrategia y oportunidades.$f$),
  ($f$O5$f$, 'oportunidad', $f$Subir tu pensión con Modalidad 40$f$, '{mod40_retro,mod40_prospectiva}', 90, $f$Es cotizar por tu cuenta con el salario que elijas para subir tu salario promedio y sumar semanas; en Ley 73 puede multiplicar tu pensión.$f$, $f$*Retroactiva*: aplica hoy y tiene 59.8 años o más — se pagan meses pasados en una sola exhibición. *Prospectiva*: se cotiza de aquí al retiro. El expediente trae la **fecha límite de inscripción**.$f$, $f$1. La pensión de Ley 73 usa el promedio de tus últimas 250 semanas. Modalidad 40 te deja escoger ese salario (hasta 25 UMA) justo en las semanas que más pesan.
2. Dos números, siempre juntos: **cuánto cuesta** y **cuánto sube la pensión**. La mesa los da con la fecha de trámite que elijas, al día.
3. La retroactiva tiene ventana: si se cierra, ya no se puede. Es la única urgencia real de la ficha.$f$, $f$- *"No tengo ese dinero"* — Se puede financiar: con el propio retroactivo de la pensión, con Infonavit, con SAR 92 / Retiro 97, o con un crédito sobre la pensión futura.
- *"¿En cuánto tiempo lo recupero?"* — Divide el costo entre el aumento mensual; enséñalo en la mesa. El valor de que sea vitalicio es mucho mayor al costo.
- *"¿Cuánto tarda la pensión?"* — Con Modalidad 40 de por medio, alrededor de **4 meses** desde el pago de las líneas de captura (sin ella, alrededor de 1 mes).$f$, $f$Constancia de baja del IMSS (cliente) → constancia de semanas (Trol) → cálculo del retroactivo y líneas de captura (Trol). En prospectiva: definir salario de inscripción y plan de pagos → inscripción y primera línea.$f$, $f$Criterio para ofrecerla activamente: más de 950 semanas, más de 40 semanas de hueco y más de 59.5 años. El costo se calcula **día por día**: redondear por mes produce errores de miles de pesos. Financiamiento al 25% anual sobre saldo insoluto; orden de cobro al liquidar: retroactivo de pensión → Infonavit → SAR 92 / Retiro 97 → crédito sobre la pensión sólo si falta. Ejecuta Viraal en la retroactiva.$f$, $f$Estrategia y oportunidades (escenario cerrado de la calculadora).$f$),
  ($f$O6$f$, 'oportunidad', $f$Ya podrías pensionarte$f$, '{pension_hoy}', 100, $f$Ya cumples edad, semanas y derechos: puedes iniciar tu trámite hoy, y cada mes que pasa es pensión que no cobras.$f$, $f$Ley 73 · 60 años o más · 500 semanas o más · derechos vigentes.$f$, $f$1. Primero la buena noticia, con su número.
2. **El retroactivo**: el IMSS paga hasta **12 meses** hacia atrás, contados desde lo más tardío entre su baja y el día que cumplió 60. No desde los 60 a secas.
3. Antes de tramitar, revisar dos cosas que ya no se pueden arreglar después: si esperar un escalón de edad la sube (T3) y si Modalidad 40 aplica (O5).
4. El trámite ante el IMSS es gratis. Trol acompaña; no pide anticipos en efectivo ni garantiza montos.$f$, $f$- *"¿Cuánto me van a dar de retroactivo?"* — El número del sistema está **proyectado**: si se calculó cuando estaba empleado, asumió que seguiría cotizando. Corrígelo en vivo con su fecha real de baja.$f$, $f$Cliente: identificación, CURP y NSS, estado de cuenta AFORE reciente, CLABE para el depósito. Trol: constancia de semanas y solicitud de pensión.$f$, $f$A quién llamar primero: a quien **más está perdiendo** (retroactivo topado en 12 meses), no al de mayor pensión. Honorario del acompañamiento: depende del caso.$f$, $f$Resumen de su situación · Estrategia.$f$),
  ($f$O7$f$, 'oportunidad', $f$Tu Infonavit al pensionarte$f$, '{}', 110, $f$Lo que tus patrones aportaron a Infonavit es tuyo: en Ley 73 se te devuelve al pensionarte, pero mientras tanto crece muy lento, y en Ley 97 puede perderse dentro de la pensión mínima si no se mueve antes.$f$, null, $f$1. Ley 73: saldo no utilizado = dinero en efectivo al pensionarte; mientras tanto crece muy lento.
2. Ley 97: si AFORE + Infonavit no alcanzan la mínima, el IMSS toma los dos saldos. **Rescatarlo antes** hace tres cosas: se quita el castigo (factor 0.81), sales de debajo de la mínima, y el dinero capitaliza.
3. Enseña la tabla "a la pensión" contra "rescatando": la cuenta individual casi no se mueve; **toda la estrategia vive en la columna de encima**.$f$, $f$- *"¿Qué me cuesta?"* — El plan se arma para que sea sin costo: lo paga la constructora. Con saldo de hoy menor a $169,000 se hace por otra vía que cobra 20% de lo que sale.
- *"Me pensiono en unos meses"* — Entonces probablemente no conviene: con menos de un año de horizonte el 20% no se paga solo.$f$, null, $f$El saldo que muestra el sistema puede ser **estimado**: para una propuesta formal se necesita el real, de Mi Cuenta Infonavit. Los términos (piso de $169,000 y 20%) son comerciales y se editan en Inmuebles. El tratamiento fiscal del rescate **no está modelado**. Lo que sí cuesta es trámite y confianza: dilo con palabras.$f$, $f$Infonavit (asesoría Infonavit ligada).$f$),
  ($f$O8$f$, 'oportunidad', $f$Usar tu Infonavit hoy$f$, '{mejoravit_activo,credito_infonavit_activo,compra_inmueble}', 120, $f$Si estás cotizando y no tienes crédito vigente, tu subcuenta te da acceso a dinero hoy: para mejorar tu casa, como crédito o para comprar.$f$, $f$Cotizando y sin crédito Infonavit vigente. *Mejoravit*: saldo entre $20,000 y $349,999. *Crédito*: saldo de $500,000 o más. *Compra*: saldo de $150,000 o más con capacidad de crédito.$f$, $f$1. Pregunta primero qué quiere hacer; no ofrezcas las tres.
2. Mejoravit: tope de **$169,000 o 90% del saldo**, lo que sea menor. El crédito se liquida contra la subcuenta a los 2 meses de dejar de cotizar, así que los intereses no corren todo el plazo.
3. Conecta con la pensión: el dinero que saca hoy puede financiar Modalidad 40 (O5).$f$, null, $f$Compra: identificación, CURP, constancia de situación fiscal, acta de nacimiento, acta de matrimonio, comprobante de domicilio y acceso a Mi Cuenta Infonavit; Trol llena solicitud, anexos, precalificación, taller y validaciones.$f$, $f$A Trol el Mejoravit le cuesta **13.5%**. Estrategia Mejoravit → Modalidad 40 → crédito de pensión: Trol cobra 20% del Mejoravit + $800 al mes desde el mes 1 + 25% anual sólo sobre capital desembolsado. Atiende la línea Infonavit (Frans). Ejecuta Astuto.$f$, $f$Infonavit.$f$),
  ($f$O9$f$, 'oportunidad', $f$Un crédito sobre tu pensión$f$, '{credito_pension}', 130, $f$Si ya cobras tu pensión del IMSS puedes tener un crédito que se descuenta de ella, con la mensualidad topada por tu capacidad.$f$, $f$Pensionado verificado en nómina IMSS, con capacidad de descuento y sin préstamos.$f$, $f$1. Explica por qué sabemos que es pensionado: revisó su pensión con Trol.
2. Una sola pregunta: ¿ya le descuentan algún crédito?
3. El monto lo fija la financiera. Tú mandas opciones; no cotizas.$f$, null, null, $f$**Nunca montos por WhatsApp** a un adulto mayor: convierte el aviso en oferta. Se dice "precalifica", nunca "califica". No se menciona lo visto en nómina. Confirmar la **edad máxima** de la financiera antes de ofrecer a mayores de 70. Verónica atiende a los interesados; Martín (Viraal / Credifintech) cierra.$f$, $f$Ahorro e inversión **[CONFIRMAR sección]**.$f$),
  ($f$O10$f$, 'oportunidad', $f$Tu AFORE: registrarla y estar en una buena$f$, '{cuenta_sin_registrar,cambio_afore}', 140, $f$Todas las AFORE invierten tu dinero pero no rinden igual; estar en una de las mejores no cuesta nada, y sin cuenta registrada no puedes ni ahorrar ni hacer trámites.$f$, $f$La cuenta aparece sin registrar ante la CONSAR; o su AFORE está fuera de las 3 mejores por rendimiento neto.$f$, $f$1. En Ley 97 la AFORE mueve fuerte el saldo final; en Ley 73 importa menos para la pensión y más para lo que recibe en efectivo.
2. Si ya está en una de las mejores, díselo: va bien, y lo que sigue es ahorro voluntario.
3. **Transparencia siempre**: SURA está entre las mejores de su generación y es aliada de Trol. Se dice.$f$, null, null, $f$Nunca prometer rendimientos. El traspaso es gratuito y lo cierra un agente certificado. El número del comparativo es una **simulación** con su historia laboral real y precios históricos de CONSAR: por eso "rondaría". Ejecuta un asesor certificado de AFORE, en alianza con Astuto.$f$, $f$Ahorro e inversión.$f$),
  ($f$O11$f$, 'oportunidad', $f$Ahorrar para cerrar la brecha$f$, '{ahorro_voluntario}', 150, $f$Entre lo que esperas recibir y lo que te tocaría hay una diferencia; el ahorro voluntario es la forma más directa y barata de acortarla.$f$, null, $f$1. Parte de **su** número: la brecha mensual del expediente.
2. Tres vehículos, todos con beneficio fiscal: ahorro voluntario en AFORE (bajo costo, automatizable, p. ej. Millas para el Retiro), seguros para el retiro (protección mientras llegas al retiro) y PPR (flexibilidad en cómo invertir).
3. En Ley 73 **no sube la pensión**: sube lo que recibe en efectivo. Dilo: es donde más se confunde la gente.$f$, null, null, $f$Requiere cuenta registrada (O10). Recomendaciones específicas de producto: Trol les ayuda con la gestión y las cotizaciones.$f$, $f$Ahorro e inversión.$f$);
